name: chopper_generator
description: Chopper is an http client generator using source_gen and inspired from retrofit
version: 3.0.5
homepage: https://hadrien-lejard.gitbook.io/chopper
repository: https://github.com/lejard-h/chopper
author: Hadrien Lejard <hadrien.lejard@gmail.com>

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.8
  analyzer: ^0.39.10
  build: ^1.2.2
  logging: ^0.11.3+2
  source_gen: ^0.9.8
  chopper: ^3.0.6
  code_builder: ^3.5.0
  dart_style: ^1.3.3
  built_collection: ^4.3.2

dev_dependencies:
  test: ^1.15.5
  pedantic: ^1.9.2
